services:
  mvp_db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB = ${POSTGRES_DB}
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    restart: always
    container_name: mvp_game_db
